### ISSUE TITLE
blob urls

### ISSUE THREAD

**Issue by cdebaixo** [gualtierofrigerio/WKWebViewDownloadHelper#4]
Is it possible to download a blob:url using your WKWebViewDownloadHelper?
I have been trying to generate javascript code in WKWebView to do this with no success.

**Comment by gualtierofrigerio** [comment]
try to have a look at a previous issue
https://github.com/gualtierofrigerio/WKWebViewDownloadHelper/issues/2
does it help?

**Comment by cdebaixo** [comment]
I have implemented decidePolicyFor navigationAction function as suggested.
My first step is to obtain the blob:url from the source website and the navigationAction function is being called but it doesn't complete i.e. the estimatedProgress value for the navigation never reaches 1.0 and my resulting html does not contain the blob:url value. If I use the observeValue forKeyPath function it does complete correctly. However it seems that I cannot use the observeValue function and decidePolicyFor function in the same WKWebView. It looks as though I am missing something. Your help would be appreciated.
